# Developer Tool
when@dev:
  _errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.php'
    prefix: /_error
  web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.php'
    prefix: /_wdt
  web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.php'
    prefix: /_profiler

# Thor Api Documentation
thor:
  resource: '@ApiBundle/Thor/Controller'
  type: attribute

# All Modules
panel:
  resource: "../src/*/routes.yaml"